#Copyright (c) 2024 Cisco and/or its affiliates.
#
#This software is licensed to you under the terms of the Cisco Sample
#Code License, Version 1.1 (the "License"). You may obtain a copy of the
#License at
#
#               https://developer.cisco.com/docs/licenses
#
#All use of the material herein must be in accordance with the terms of
#the License. All rights not expressly granted by the License are
#reserved. Unless required by applicable law or agreed to separately in
#writing, software distributed under the License is distributed on an "AS
#IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#or implied.


####
# variables:
# customerId = CustomerId
# networkSubnet = Transfernet for Service Graph
# dhcpServer = DHCP Server for Relay Policy
# networkName = Name of the Network


#### This playbook deletes a network from NDO

- name: PLAY 1 Delete Network
  hosts: all
 # connection: local
  vars:
  
      ansible_connection: ansible.netcommon.httpapi
      ansible_network_os: cisco.nd.nd
      ansible_httpapi_use_ssl: True


  tasks:
   - set_fact:
      ndo_login: &ndo_login
        host: "{{ inventory_hostname }}"
        username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
        password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
        use_ssl: yes
        validate_certs: no



   - name: Remove a site EPG
     cisco.mso.mso_schema_site_anp_epg:
       <<: *ndo_login
       schema: "DHC_NG_{{ customerId }}"
       template: "DC1_DHC_NG_{{ customerId }}"
       site: DC1
       anp: "DHC_NG_{{ customerId }}_ANP"
       epg: "{{ networkName }}_EPG"
       state: absent
     delegate_to: localhost
     ignore_errors: yes

   - name: Remove a new EPG
     cisco.mso.mso_schema_template_anp_epg:
       <<: *ndo_login
       schema: "DHC_NG_{{ customerId }}"
       template: "DC1_DHC_NG_{{ customerId }}"
       anp: "DHC_NG_{{ customerId }}_ANP"
       epg: "{{ networkName }}_EPG"
       bd:
        name: "{{ networkName }}_BD"
       state: absent
     delegate_to: localhost
     ignore_errors: yes


   - name: Remove a new BD
     cisco.mso.mso_schema_template_bd:
       <<: *ndo_login
       schema: "DHC_NG_{{ customerId }}"
       template: "DC1_DHC_NG_{{ customerId }}"
       bd: "{{ networkName }}_BD"
       vrf:
         name: "DHC_NG_{{ customerId }}_VRF"
         template: "SHARED_DHC_NG_{{ customerId }}"
       dhcp_policy:
         name: "DHC_NG_{{ customerId }}_DHCPRELAY"
         version: "1"       
       state: absent
       layer2_stretch: false
     delegate_to: localhost
     ignore_errors: yes


   - name: Remove a new site BD
     cisco.mso.mso_schema_site_bd:
       <<: *ndo_login
       schema: "DHC_NG_{{ customerId }}"
       site: "DC1"
       template: "DC1_DHC_NG_{{ customerId }}"

       bd: "{{ networkName }}_BD"
       state: absent
     delegate_to: localhost
     ignore_errors: yes











   - name: Deploy a schema template
     cisco.mso.ndo_schema_template_deploy:
       <<: *ndo_login
       schema: "DHC_NG_{{ customerId }}"
       template: "SHARED_DHC_NG_{{ customerId }}"
       state: deploy
     delegate_to: localhost
     ignore_errors: yes


   - name: Deploy a schema template
     cisco.mso.ndo_schema_template_deploy:
       <<: *ndo_login
       schema: "DHC_NG_{{ customerId }}"
       template: "DC1_DHC_NG_{{ customerId }}"
       state: deploy
     delegate_to: localhost
     ignore_errors: yes




 



 




